// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ActiveTestRunsResponse mirrors swagger definition "internal_webui.ActiveTestRunsResponse".
type ActiveTestRunsResponse struct {
	Chaos []ActiveWorkloadItem `json:"chaos,omitempty"`
	Fuzz  []ActiveWorkloadItem `json:"fuzz,omitempty"`
	Runs  []TestRun            `json:"runs,omitempty"`
}
