// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ActiveWorkloadItem mirrors swagger definition "internal_webui.ActiveWorkloadItem".
type ActiveWorkloadItem struct {
	CancelURL string `json:"cancelUrl,omitempty"`
	ID        string `json:"id,omitempty"`
	// "fuzz" | "chaos"
	Kind        string `json:"kind,omitempty"`
	Name        string `json:"name,omitempty"`
	Namespace   string `json:"namespace,omitempty"`
	OpenURL     string `json:"openUrl,omitempty"`
	StartedAt   string `json:"startedAt,omitempty"`
	Status      string `json:"status,omitempty"`
	ProgressPct int64  `json:"progressPct,omitempty"`
}
