// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// AffectedResource mirrors swagger definition "internal_chaos.AffectedResource".
type AffectedResource struct {
	// killed, restarted, scaled, drained, partitioned
	Action string `json:"action,omitempty"`
	// Pod, Deployment, Node, NetworkPolicy
	Kind      string `json:"kind,omitempty"`
	Name      string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Recovered bool   `json:"recovered,omitempty"`
}
