// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// APITesterProtocol mirrors swagger definition "mockarty_internal_model.APITesterProtocol".
type APITesterProtocol string

// Enumerated values for APITesterProtocol.
const (
	APITesterProtocolHTTP        APITesterProtocol = "http"
	APITesterProtocolSOAP        APITesterProtocol = "soap"
	APITesterProtocolGRPC        APITesterProtocol = "grpc"
	APITesterProtocolMCP         APITesterProtocol = "mcp"
	APITesterProtocolGraphQL     APITesterProtocol = "graphql"
	APITesterProtocolSocket      APITesterProtocol = "socket"
	APITesterProtocolSSE         APITesterProtocol = "sse"
	APITesterProtocolKafka       APITesterProtocol = "kafka"
	APITesterProtocolRabbitMQ    APITesterProtocol = "rabbitmq"
	APITesterProtocolSMTP        APITesterProtocol = "smtp"
	APITesterProtocolTests       APITesterProtocol = "tests"
	APITesterProtocolPerformance APITesterProtocol = "performance"
)
