// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// APIKey mirrors swagger definition "internal_auth.APIKey".
type APIKey struct {
	Metadata           map[string]any `json:"metadata,omitempty"`
	CreatedAt          string         `json:"created_at,omitempty"`
	CreatedBy          string         `json:"created_by,omitempty"`
	Description        string         `json:"description,omitempty"`
	ExpiresAt          string         `json:"expires_at,omitempty"`
	ID                 string         `json:"id,omitempty"`
	LastUsedAt         string         `json:"last_used_at,omitempty"`
	Name               string         `json:"name,omitempty"`
	Namespace          string         `json:"namespace,omitempty"`
	UpdatedAt          string         `json:"updated_at,omitempty"`
	UserID             string         `json:"user_id,omitempty"`
	UserLogin          string         `json:"user_login,omitempty"`
	AllowedActions     []string       `json:"allowed_actions,omitempty"`
	RateLimitPerDay    int64          `json:"rate_limit_per_day,omitempty"`
	RateLimitPerHour   int64          `json:"rate_limit_per_hour,omitempty"`
	RateLimitPerMinute int64          `json:"rate_limit_per_minute,omitempty"`
	Enabled            bool           `json:"enabled,omitempty"`
}
