// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// AssertAction mirrors swagger definition "mockarty_internal_model.AssertAction".
type AssertAction string

// Enumerated values for AssertAction.
const (
	AssertActionEquals      AssertAction = "equals"
	AssertActionContains    AssertAction = "contains"
	AssertActionNotEquals   AssertAction = "not_equals"
	AssertActionNotContains AssertAction = "not_contains"
	AssertActionAny         AssertAction = "any"
	AssertActionNotEmpty    AssertAction = "notEmpty"
	AssertActionEmpty       AssertAction = "empty"
	AssertActionMatches     AssertAction = "matches"
)
