// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CStore mirrors swagger definition "mockarty_internal_model.CStore".
type CStore map[string]any
