// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Callback mirrors swagger definition "mockarty_internal_model.Callback".
type Callback struct {
	Headers          map[string]string `json:"headers,omitempty"`
	Trigger          CallbackTrigger   `json:"trigger,omitempty"`
	Type             CallbackType      `json:"type,omitempty"`
	Body             any               `json:"body,omitempty"`
	KafkaBrokers     string            `json:"kafkaBrokers,omitempty"`
	KafkaKey         string            `json:"kafkaKey,omitempty"`
	KafkaPassword    string            `json:"kafkaPassword,omitempty"`
	KafkaTopic       string            `json:"kafkaTopic,omitempty"`
	KafkaUsername    string            `json:"kafkaUsername,omitempty"`
	Method           string            `json:"method,omitempty"`
	RabbitExchange   string            `json:"rabbitExchange,omitempty"`
	RabbitQueue      string            `json:"rabbitQueue,omitempty"`
	RabbitRoutingKey string            `json:"rabbitRoutingKey,omitempty"`
	RabbitURL        string            `json:"rabbitURL,omitempty"`
	URL              string            `json:"url,omitempty"`
	RetryCount       int64             `json:"retryCount,omitempty"`
	RetryDelay       int64             `json:"retryDelay,omitempty"`
	Timeout          int64             `json:"timeout,omitempty"`
	Async            bool              `json:"async,omitempty"`
	KafkaUseSASL     bool              `json:"kafkaUseSASL,omitempty"`
	KafkaUseTLS      bool              `json:"kafkaUseTLS,omitempty"`
	RabbitMandatory  bool              `json:"rabbitMandatory,omitempty"`
}
