// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CallbackTrigger mirrors swagger definition "mockarty_internal_model.CallbackTrigger".
type CallbackTrigger string

// Enumerated values for CallbackTrigger.
const (
	CallbackTriggerOnSuccess CallbackTrigger = "on_success"
	CallbackTriggerOnError   CallbackTrigger = "on_error"
	CallbackTriggerAlways    CallbackTrigger = "always"
)
