// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CallbackType mirrors swagger definition "mockarty_internal_model.CallbackType".
type CallbackType string

// Enumerated values for CallbackType.
const (
	CallbackTypeHTTP     CallbackType = "http"
	CallbackTypeKafka    CallbackType = "kafka"
	CallbackTypeRabbitMQ CallbackType = "rabbitmq"
)
