// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ClusterSnapshot mirrors swagger definition "internal_chaos.ClusterSnapshot".
type ClusterSnapshot struct {
	ClusterID       string                  `json:"clusterId,omitempty"`
	CreatedAt       string                  `json:"createdAt,omitempty"`
	ExperimentID    string                  `json:"experimentId,omitempty"`
	ID              string                  `json:"id,omitempty"`
	RestoredAt      string                  `json:"restoredAt,omitempty"`
	ConfigMaps      []ConfigMapSnapshot     `json:"configMaps,omitempty"`
	Deployments     []DeploymentSnapshot    `json:"deployments,omitempty"`
	NetworkPolicies []NetworkPolicySnapshot `json:"networkPolicies,omitempty"`
	Nodes           []NodeSnapshot          `json:"nodes,omitempty"`
	RestoreErrors   []string                `json:"restoreErrors,omitempty"`
	Restored        bool                    `json:"restored,omitempty"`
}
