// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CollectionTestReport mirrors swagger definition "mockarty_internal_model.CollectionTestReport".
type CollectionTestReport struct {
	Summary        map[string]any `json:"summary,omitempty"`
	AiAnalysis     string         `json:"aiAnalysis,omitempty"`
	CollectionID   string         `json:"collectionId,omitempty"`
	CollectionName string         `json:"collectionName,omitempty"`
	ExecutedAt     string         `json:"executedAt,omitempty"`
	ExecutorID     string         `json:"executorId,omitempty"`
	ID             string         `json:"id,omitempty"`
	Name           string         `json:"name,omitempty"`
	Status         string         `json:"status,omitempty"`
	PerfReport     []int64        `json:"perfReport,omitempty"`
	RequestReports []TestReport   `json:"requestReports,omitempty"`
	Duration       Duration       `json:"duration,omitempty"`
	FailedRequests int64          `json:"failedRequests,omitempty"`
	FailedTests    int64          `json:"failedTests,omitempty"`
	PassedRequests int64          `json:"passedRequests,omitempty"`
	PassedTests    int64          `json:"passedTests,omitempty"`
	TotalRequests  int64          `json:"totalRequests,omitempty"`
	TotalTests     int64          `json:"totalTests,omitempty"`
}
