// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Condition mirrors swagger definition "mockarty_internal_model.Condition".
type Condition struct {
	AssertAction  AssertAction `json:"assertAction,omitempty"`
	Decode        Decode       `json:"decode,omitempty"`
	Path          string       `json:"path,omitempty"`
	Value         any          `json:"value,omitempty"`
	ValueFromFile string       `json:"valueFromFile,omitempty"`
	SortArray     bool         `json:"sortArray,omitempty"`
}
