// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ConfigMapSnapshot mirrors swagger definition "internal_chaos.ConfigMapSnapshot".
type ConfigMapSnapshot struct {
	Data      map[string]string `json:"data,omitempty"`
	Name      string            `json:"name,omitempty"`
	Namespace string            `json:"namespace,omitempty"`
}
