// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ContentResponse mirrors swagger definition "mockarty_internal_model.ContentResponse".
type ContentResponse struct {
	Decode              Decode              `json:"decode,omitempty"`
	Headers             map[string][]string `json:"headers,omitempty"`
	SOAPFault           SOAPFault           `json:"soapFault,omitempty"`
	SSEEventChain       SSEEventChain       `json:"sseEventChain,omitempty"`
	Error               string              `json:"error,omitempty"`
	Payload             any                 `json:"payload,omitempty"`
	PayloadTemplatePath string              `json:"payloadTemplatePath,omitempty"`
	ErrorDetails        []ErrorDetails      `json:"errorDetails,omitempty"`
	GraphQLErrors       []GraphQLError      `json:"graphqlErrors,omitempty"`
	Delay               int64               `json:"delay,omitempty"`
	StatusCode          int64               `json:"statusCode,omitempty"`
	MCPIsError          bool                `json:"mcpIsError,omitempty"`
}
