// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CreateDelegatedCredentialRequest mirrors swagger definition "internal_auth.CreateDelegatedCredentialRequest".
type CreateDelegatedCredentialRequest struct {
	Metadata       map[string]any `json:"metadata,omitempty"`
	Description    string         `json:"description,omitempty"`
	ExpiresAt      string         `json:"expires_at,omitempty"`
	Name           string         `json:"name,omitempty"`
	AllowedActions []string       `json:"allowed_actions,omitempty"`
	Namespaces     []string       `json:"namespaces,omitempty"`
}
