// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CreateAPITokenResponse mirrors swagger definition "internal_auth.CreateAPITokenResponse".
type CreateAPITokenResponse struct {
	// Token metadata (without hash)
	TokenInfo APIKey `json:"token_info,omitempty"`
	Message   string `json:"message,omitempty"`
	// Plain token (shown only once)
	Token string `json:"token,omitempty"`
}
