// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// CreateDelegatedCredentialResponse mirrors swagger definition "internal_auth.CreateDelegatedCredentialResponse".
type CreateDelegatedCredentialResponse struct {
	Credential DelegatedCredential `json:"credential,omitempty"`
	Message    string              `json:"message,omitempty"`
	Token      string              `json:"token,omitempty"`
}
