// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// DelegatedCredential mirrors swagger definition "internal_auth.DelegatedCredential".
type DelegatedCredential struct {
	Metadata  map[string]any `json:"metadata,omitempty"`
	CreatedAt string         `json:"created_at,omitempty"`
	// Description is free text for humans; never an authorization input.
	Description string `json:"description,omitempty"`
	ExpiresAt   string `json:"expires_at,omitempty"`
	ID          string `json:"id,omitempty"`
	// IssuerCredentialID is set when another DELEGATED credential minted this one. It is the value that stops a delegated credential from managing its issuer's credentials: an issuer may only touch rows whose IssuerCredentialID equals its own id.
	IssuerCredentialID string `json:"issuer_credential_id,omitempty"`
	IssuerUserEmail    string `json:"issuer_user_email,omitempty"`
	// IssuerUserID owns the credential: the only user principal allowed to list, read, rotate or revoke it. It is also the identity the credential assumes on the wire (delegation, not impersonation of a new principal).
	IssuerUserID    string `json:"issuer_user_id,omitempty"`
	IssuerUserLogin string `json:"issuer_user_login,omitempty"`
	// IssuerUserRole / IssuerUserEmail / IssuerUserLogin are resolved from the issuer's users row at validation time (never stored on the credential, so a role change or disable takes effect as soon as the cache entry expires).
	IssuerUserRole string   `json:"issuer_user_role,omitempty"`
	LastUsedAt     string   `json:"last_used_at,omitempty"`
	Name           string   `json:"name,omitempty"`
	RevokedAt      string   `json:"revoked_at,omitempty"`
	TokenPrefix    string   `json:"token_prefix,omitempty"`
	UpdatedAt      string   `json:"updated_at,omitempty"`
	AllowedActions []string `json:"allowed_actions,omitempty"`
	// Namespaces and AllowedActions are the frozen scope, stored as a JSON array in every dialect.
	Namespaces []string `json:"namespaces,omitempty"`
}
