// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// DeploymentSnapshot mirrors swagger definition "internal_chaos.DeploymentSnapshot".
type DeploymentSnapshot struct {
	Image     string `json:"image,omitempty"`
	Name      string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Replicas  int64  `json:"replicas,omitempty"`
}
