// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Duration mirrors swagger definition "time.Duration".
type Duration int64

// Enumerated values for Duration.
const (
	DurationMinDuration Duration = -9223372036854775808
	DurationMaxDuration Duration = 9223372036854775807
	DurationNanosecond  Duration = 1
	DurationMicrosecond Duration = 1000
	DurationMillisecond Duration = 1000000
	DurationSecond      Duration = 1000000000
	DurationMinute      Duration = 60000000000
	DurationHour        Duration = 3600000000000
)
