// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ErrorDetailsType mirrors swagger definition "mockarty_internal_model.ErrorDetailsType".
type ErrorDetailsType string

// Enumerated values for ErrorDetailsType.
const (
	ErrorDetailsTypeBadRequest          ErrorDetailsType = "badRequest"
	ErrorDetailsTypeHelp                ErrorDetailsType = "help"
	ErrorDetailsTypeDebugInfo           ErrorDetailsType = "debugInfo"
	ErrorDetailsTypeInfo                ErrorDetailsType = "errorInfo"
	ErrorDetailsTypeLocalizedMessage    ErrorDetailsType = "localizedMessage"
	ErrorDetailsTypePreconditionFailure ErrorDetailsType = "preconditionFailure"
	ErrorDetailsTypeQuotaFailure        ErrorDetailsType = "quotaFailure"
	ErrorDetailsTypeRequestInfo         ErrorDetailsType = "requestInfo"
	ErrorDetailsTypeResourceInfo        ErrorDetailsType = "resourceInfo"
	ErrorDetailsTypeRetryInfo           ErrorDetailsType = "retryInfo"
)
