// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ErrorDetails mirrors swagger definition "mockarty_internal_model.ErrorDetails".
type ErrorDetails struct {
	Details map[string]any   `json:"details,omitempty"`
	Type    ErrorDetailsType `json:"type,omitempty"`
}
