// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ErrorResponse mirrors swagger definition "mockarty_internal_model.ErrorResponse".
type ErrorResponse struct {
	Error string `json:"error,omitempty"`
}
