// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Extract mirrors swagger definition "mockarty_internal_model.Extract".
type Extract struct {
	CStore CStore `json:"cStore,omitempty"`
	GStore GStore `json:"gStore,omitempty"`
	MStore MStore `json:"mStore,omitempty"`
}
