// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FaultType mirrors swagger definition "internal_chaos.FaultType".
type FaultType string

// Enumerated values for FaultType.
const (
	FaultTypePodKill           FaultType = "pod_kill"
	FaultTypePodKillRandom     FaultType = "pod_kill_random"
	FaultTypeNetworkPartition  FaultType = "network_partition"
	FaultTypeNetworkDelay      FaultType = "network_delay"
	FaultTypeNetworkLoss       FaultType = "network_loss"
	FaultTypeDeploymentRestart FaultType = "deployment_restart"
	FaultTypeScale             FaultType = "scale"
	FaultTypeNodeDrain         FaultType = "node_drain"
	FaultTypeResourceStress    FaultType = "resource_stress"
	FaultTypeDNSDisruption     FaultType = "dns_disruption"
	FaultTypeIOChaos           FaultType = "io_chaos"
	FaultTypeTimeChaos         FaultType = "time_chaos"
)
