// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FaultConfig mirrors swagger definition "internal_chaos.FaultConfig".
type FaultConfig struct {
	Parameters     map[string]any `json:"parameters,omitempty"`
	Type           FaultType      `json:"type,omitempty"`
	Duration       string         `json:"duration,omitempty"`
	IoPath         string         `json:"ioPath,omitempty"`
	SpoofIP        string         `json:"spoofIP,omitempty"`
	StressType     string         `json:"stressType,omitempty"`
	TargetDomain   string         `json:"targetDomain,omitempty"`
	CorruptPercent int64          `json:"corruptPercent,omitempty"`
	CpuCores       int64          `json:"cpuCores,omitempty"`
	GracePeriodSec int64          `json:"gracePeriodSec,omitempty"`
	IntervalSec    int64          `json:"intervalSec,omitempty"`
	IoErrPercent   int64          `json:"ioErrPercent,omitempty"`
	IoLatencyMs    int64          `json:"ioLatencyMs,omitempty"`
	JitterMs       int64          `json:"jitterMs,omitempty"`
	LatencyMs      int64          `json:"latencyMs,omitempty"`
	LossPercent    int64          `json:"lossPercent,omitempty"`
	MemoryMB       int64          `json:"memoryMB,omitempty"`
	Replicas       int64          `json:"replicas,omitempty"`
	TimeOffsetSec  int64          `json:"timeOffsetSec,omitempty"`
}
