// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindRabbitMQResponse mirrors swagger definition "mockarty_internal_model.FindRabbitMQResponse".
type FindRabbitMQResponse struct {
	Error         MessagingError      `json:"error,omitempty"`
	OutputHeaders map[string]string   `json:"outputHeaders,omitempty"`
	OutputProps   RabbitMQOutputProps `json:"outputProps,omitempty"`
	Data          any                 `json:"data,omitempty"`
	Delay         int64               `json:"delay,omitempty"`
}
