// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindKafkaResponse mirrors swagger definition "mockarty_internal_model.FindKafkaResponse".
type FindKafkaResponse struct {
	Error                MessagingError    `json:"error,omitempty"`
	OutputHeaders        map[string]string `json:"outputHeaders,omitempty"`
	OutputMessageHeaders map[string]string `json:"outputMessageHeaders,omitempty"`
	Data                 any               `json:"data,omitempty"`
	Delay                int64             `json:"delay,omitempty"`
}
