// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindKafkaRequest mirrors swagger definition "mockarty_internal_model.FindKafkaRequest".
type FindKafkaRequest struct {
	Headers       map[string]string `json:"headers,omitempty"`
	ConsumerGroup string            `json:"consumerGroup,omitempty"`
	Data          any               `json:"data,omitempty"`
	Namespace     string            `json:"namespace,omitempty"`
	ServerName    string            `json:"serverName,omitempty"`
	Topic         string            `json:"topic,omitempty"`
}
