// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindGrpcResponse mirrors swagger definition "mockarty_internal_model.FindGrpcResponse".
type FindGrpcResponse struct {
	Error           GrpcError         `json:"error,omitempty"`
	Meta            map[string]string `json:"meta,omitempty"`
	Proxy           Proxy             `json:"proxy,omitempty"`
	Data            any               `json:"data,omitempty"`
	StreamResponses []any             `json:"streamResponses,omitempty"`
	Delay           int64             `json:"delay,omitempty"`
}
