// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindSocketRequest mirrors swagger definition "mockarty_internal_model.FindSocketRequest".
type FindSocketRequest struct {
	Data           any    `json:"data,omitempty"`
	Event          string `json:"event,omitempty"`
	MockServerName string `json:"mockServerName,omitempty"`
	Namespace      string `json:"namespace,omitempty"`
	ServerName     string `json:"serverName,omitempty"`
}
