// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindGrpcRequest mirrors swagger definition "mockarty_internal_model.FindGrpcRequest".
type FindGrpcRequest struct {
	Meta       map[string][]string `json:"meta,omitempty"`
	Data       any                 `json:"data,omitempty"`
	Method     string              `json:"method,omitempty"`
	Namespace  string              `json:"namespace,omitempty"`
	ServerName string              `json:"serverName,omitempty"`
	Service    string              `json:"service,omitempty"`
}
