// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindSmtpResponse mirrors swagger definition "mockarty_internal_model.FindSmtpResponse".
type FindSmtpResponse struct {
	Headers       map[string]string `json:"headers,omitempty"`
	MockID        string            `json:"mockId,omitempty"`
	StatusMessage string            `json:"statusMessage,omitempty"`
	Delay         int64             `json:"delay,omitempty"`
	StatusCode    int64             `json:"statusCode,omitempty"`
	AcceptMail    bool              `json:"acceptMail,omitempty"`
	Found         bool              `json:"found,omitempty"`
	StoreEmail    bool              `json:"storeEmail,omitempty"`
}
