// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindRabbitMQRequest mirrors swagger definition "mockarty_internal_model.FindRabbitMQRequest".
type FindRabbitMQRequest struct {
	Headers    map[string]string `json:"headers,omitempty"`
	Data       any               `json:"data,omitempty"`
	Exchange   string            `json:"exchange,omitempty"`
	Namespace  string            `json:"namespace,omitempty"`
	Queue      string            `json:"queue,omitempty"`
	RoutingKey string            `json:"routingKey,omitempty"`
	ServerName string            `json:"serverName,omitempty"`
}
