// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindSocketResponse mirrors swagger definition "mockarty_internal_model.FindSocketResponse".
type FindSocketResponse struct {
	Error GrpcError `json:"error,omitempty"`
	Proxy Proxy     `json:"proxy,omitempty"`
	Data  any       `json:"data,omitempty"`
	Delay int64     `json:"delay,omitempty"`
}
