// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// FindSmtpRequest mirrors swagger definition "mockarty_internal_model.FindSmtpRequest".
type FindSmtpRequest struct {
	Headers    map[string]string `json:"headers,omitempty"`
	Body       string            `json:"body,omitempty"`
	From       string            `json:"from,omitempty"`
	Namespace  string            `json:"namespace,omitempty"`
	ServerName string            `json:"serverName,omitempty"`
	Subject    string            `json:"subject,omitempty"`
	To         []string          `json:"to,omitempty"`
}
