// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GStore mirrors swagger definition "mockarty_internal_model.GStore".
type GStore map[string]any
