// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GraphQLRequestContext mirrors swagger definition "mockarty_internal_model.GraphQLRequestContext".
type GraphQLRequestContext struct {
	Field      string      `json:"field,omitempty"`
	Operation  string      `json:"operation,omitempty"`
	Path       string      `json:"path,omitempty"`
	Type       string      `json:"type,omitempty"`
	Conditions []Condition `json:"conditions,omitempty"`
	Header     []Condition `json:"header,omitempty"`
	SortArray  bool        `json:"sortArray,omitempty"`
}
