// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GraphQLErrorLocation mirrors swagger definition "mockarty_internal_model.GraphQLErrorLocation".
type GraphQLErrorLocation struct {
	Column int64 `json:"column,omitempty"`
	Line   int64 `json:"line,omitempty"`
}
