// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GraphQLError mirrors swagger definition "mockarty_internal_model.GraphQLError".
type GraphQLError struct {
	Extensions map[string]any         `json:"extensions,omitempty"`
	Message    string                 `json:"message,omitempty"`
	Locations  []GraphQLErrorLocation `json:"locations,omitempty"`
	Path       []any                  `json:"path,omitempty"`
}
