// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GrpcRequestContext mirrors swagger definition "mockarty_internal_model.GrpcRequestContext".
type GrpcRequestContext struct {
	Method     string      `json:"method,omitempty"`
	MethodType string      `json:"methodType,omitempty"`
	Service    string      `json:"service,omitempty"`
	Conditions []Condition `json:"conditions,omitempty"`
	Meta       []Condition `json:"meta,omitempty"`
	SortArray  bool        `json:"sortArray,omitempty"`
}
