// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// GrpcError mirrors swagger definition "mockarty_internal_model.GrpcError".
type GrpcError struct {
	Message string         `json:"message,omitempty"`
	Details []ErrorDetails `json:"details,omitempty"`
	Code    int64          `json:"code,omitempty"`
}
