// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// HttpRequestContext mirrors swagger definition "mockarty_internal_model.HttpRequestContext".
type HttpRequestContext struct {
	HTTPMethod   string      `json:"httpMethod,omitempty"`
	Route        string      `json:"route,omitempty"`
	RoutePattern string      `json:"routePattern,omitempty"`
	Conditions   []Condition `json:"conditions,omitempty"`
	Header       []Condition `json:"header,omitempty"`
	QueryParams  []Condition `json:"queryParams,omitempty"`
	// Global flag for all conditions, used if not set on individual condition
	SortArray bool `json:"sortArray,omitempty"`
}
