// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// InfraProfile mirrors swagger definition "internal_chaos.InfraProfile".
type InfraProfile struct {
	Safety            SafetyConfig `json:"safety,omitempty"`
	ClusterType       string       `json:"cluster_type,omitempty"`
	Context           string       `json:"context,omitempty"`
	CreatedAt         string       `json:"createdAt,omitempty"`
	DefaultNamespace  string       `json:"defaultNamespace,omitempty"`
	Description       string       `json:"description,omitempty"`
	ID                string       `json:"id,omitempty"`
	Kubeconfig        string       `json:"kubeconfig,omitempty"`
	KubeconfigData    string       `json:"kubeconfigData,omitempty"`
	KubeconfigPath    string       `json:"kubeconfigPath,omitempty"`
	LastCheckedAt     string       `json:"lastCheckedAt,omitempty"`
	Name              string       `json:"name,omitempty"`
	NamespaceID       string       `json:"namespaceId,omitempty"`
	Provider          string       `json:"provider,omitempty"`
	ServerURL         string       `json:"server_url,omitempty"`
	ServiceAccount    string       `json:"service_account,omitempty"`
	Status            string       `json:"status,omitempty"`
	UpdatedAt         string       `json:"updatedAt,omitempty"`
	AllowedNamespaces []string     `json:"allowed_namespaces,omitempty"`
	DeniedNamespaces  []string     `json:"denied_namespaces,omitempty"`
	AbortThreshold    int64        `json:"abort_threshold,omitempty"`
	MaxConcurrent     int64        `json:"max_concurrent,omitempty"`
	AutoRollback      bool         `json:"auto_rollback,omitempty"`
	Connected         bool         `json:"connected,omitempty"`
	InCluster         bool         `json:"inCluster,omitempty"`
}
