// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// JsonPathExtractor mirrors swagger definition "mockarty_internal_model.JsonPathExtractor".
type JsonPathExtractor struct {
	From  any    `json:"from,omitempty"`
	Jpath string `json:"jpath,omitempty"`
}
