// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// JsonPathExtractor mirrors swagger definition "mockarty_internal_model.JsonPathExtractor".
type JsonPathExtractor struct {
	From  any    `json:"from,omitempty"`
	Jpath string `json:"jpath,omitempty"`
}
