// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// KafkaRequestContext mirrors swagger definition "mockarty_internal_model.KafkaRequestContext".
type KafkaRequestContext struct {
	OutputHeaders map[string]string `json:"outputHeaders,omitempty"`
	ConsumerGroup string            `json:"consumerGroup,omitempty"`
	OutputBrokers string            `json:"outputBrokers,omitempty"`
	OutputKey     string            `json:"outputKey,omitempty"`
	OutputTopic   string            `json:"outputTopic,omitempty"`
	ServerName    string            `json:"serverName,omitempty"`
	Topic         string            `json:"topic,omitempty"`
	Conditions    []Condition       `json:"conditions,omitempty"`
	Headers       []Condition       `json:"headers,omitempty"`
	SortArray     bool              `json:"sortArray,omitempty"`
}
