// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// LoginResponse mirrors swagger definition "internal_auth.LoginResponse".
type LoginResponse struct {
	User                   UserInfo `json:"user,omitempty"`
	ExpiresAt              string   `json:"expires_at,omitempty"`
	RedirectTo             string   `json:"redirect_to,omitempty"`
	Token                  string   `json:"token,omitempty"`
	RequiresPasswordChange bool     `json:"requires_password_change,omitempty"`
}
