// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// LoginRequest mirrors swagger definition "internal_auth.LoginRequest".
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}
