// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// MStore mirrors swagger definition "mockarty_internal_model.MStore".
type MStore map[string]any
