// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// MCPRequestContext mirrors swagger definition "mockarty_internal_model.MCPRequestContext".
type MCPRequestContext struct {
	Description string      `json:"description,omitempty"`
	Method      string      `json:"method,omitempty"`
	Resource    string      `json:"resource,omitempty"`
	Tool        string      `json:"tool,omitempty"`
	Conditions  []Condition `json:"conditions,omitempty"`
	Header      []Condition `json:"header,omitempty"`
	SortArray   bool        `json:"sortArray,omitempty"`
}
