// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// MessagingError mirrors swagger definition "mockarty_internal_model.MessagingError".
type MessagingError struct {
	Message string `json:"message,omitempty"`
}
