// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// MinMaxAvg mirrors swagger definition "internal_chaos.MinMaxAvg".
type MinMaxAvg struct {
	Avg float64 `json:"avg,omitempty"`
	Max float64 `json:"max,omitempty"`
	Min float64 `json:"min,omitempty"`
}
