// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Mock mirrors swagger definition "mockarty_internal_model.Mock".
type Mock struct {
	Extract    Extract                `json:"extract,omitempty"`
	GRPC       GrpcRequestContext     `json:"grpc,omitempty"`
	GraphQL    GraphQLRequestContext  `json:"graphql,omitempty"`
	HTTP       HttpRequestContext     `json:"http,omitempty"`
	Kafka      KafkaRequestContext    `json:"kafka,omitempty"`
	MCP        MCPRequestContext      `json:"mcp,omitempty"`
	MStore     MStore                 `json:"mStore,omitempty"`
	OneOf      OneOf                  `json:"oneOf,omitempty"`
	Proxy      Proxy                  `json:"proxy,omitempty"`
	RabbitMQ   RabbitMQRequestContext `json:"rabbitmq,omitempty"`
	Response   ContentResponse        `json:"response,omitempty"`
	SMTP       SmtpRequestContext     `json:"smtp,omitempty"`
	SOAP       SoapRequestContext     `json:"soap,omitempty"`
	SSE        SSERequestContext      `json:"sse,omitempty"`
	Socket     SocketRequestContext   `json:"socket,omitempty"`
	ChainID    string                 `json:"chainId,omitempty"`
	FolderID   string                 `json:"folderId,omitempty"`
	ID         string                 `json:"id,omitempty"`
	Namespace  string                 `json:"namespace,omitempty"`
	PathPrefix string                 `json:"pathPrefix,omitempty"`
	ServerName string                 `json:"serverName,omitempty"`
	Tags       []string               `json:"tags,omitempty"`
	Webhooks   []Callback             `json:"webhooks,omitempty"`
	ClosedAt   int64                  `json:"closedAt,omitempty"`
	CreatedAt  int64                  `json:"createdAt,omitempty"`
	ExpireAt   int64                  `json:"expireAt,omitempty"`
	LastUse    int64                  `json:"lastUse,omitempty"`
	Priority   int64                  `json:"priority,omitempty"`
	Ttl        int64                  `json:"ttl,omitempty"`
	UseCounter int64                  `json:"useCounter,omitempty"`
	UseLimiter int64                  `json:"useLimiter,omitempty"`
}
