// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// NetworkPolicySnapshot mirrors swagger definition "internal_chaos.NetworkPolicySnapshot".
type NetworkPolicySnapshot struct {
	Name      string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	// true if it existed before chaos (so we DON'T delete it on restore)
	Existed bool `json:"existed,omitempty"`
}
