// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// NodeSnapshot mirrors swagger definition "internal_chaos.NodeSnapshot".
type NodeSnapshot struct {
	Name          string `json:"name,omitempty"`
	Unschedulable bool   `json:"unschedulable,omitempty"`
}
