// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// OneOfOrder mirrors swagger definition "mockarty_internal_model.OneOfOrder".
type OneOfOrder string

// Enumerated values for OneOfOrder.
const (
	OneOfOrderOrder  OneOfOrder = "order"
	OneOfOrderRandom OneOfOrder = "random"
)
