// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// OneOf mirrors swagger definition "mockarty_internal_model.OneOf".
type OneOf struct {
	Order     OneOfOrder        `json:"order,omitempty"`
	Responses []ContentResponse `json:"responses,omitempty"`
	Offset    int64             `json:"offset,omitempty"`
}
