// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// PhaseMetrics mirrors swagger definition "internal_chaos.PhaseMetrics".
type PhaseMetrics struct {
	EndTime     string    `json:"endTime,omitempty"`
	Phase       string    `json:"phase,omitempty"`
	StartTime   string    `json:"startTime,omitempty"`
	ErrorRate   float64   `json:"errorRate,omitempty"`
	Latency     MinMaxAvg `json:"latency,omitempty"`
	PodRestarts int64     `json:"podRestarts,omitempty"`
	Throughput  float64   `json:"throughput,omitempty"`
}
