// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// Proxy mirrors swagger definition "mockarty_internal_model.Proxy".
type Proxy struct {
	Target string `json:"target,omitempty"`
}
