// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// QueuedExpInfo mirrors swagger definition "internal_chaos.QueuedExpInfo".
type QueuedExpInfo struct {
	EnqueuedAt     string `json:"enqueuedAt,omitempty"`
	ExperimentID   string `json:"experimentId,omitempty"`
	ExperimentName string `json:"experimentName,omitempty"`
	Namespace      string `json:"namespace,omitempty"`
	Position       int64  `json:"position,omitempty"`
}
