// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// QueueStatus mirrors swagger definition "internal_chaos.QueueStatus".
type QueueStatus struct {
	Running         QueuedExpInfo   `json:"running,omitempty"`
	ClusterID       string          `json:"clusterId,omitempty"`
	Queued          []QueuedExpInfo `json:"queued,omitempty"`
	EstimatedWaitMs int64           `json:"estimatedWaitMs,omitempty"`
}
