// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// RabbitMQRequestContext mirrors swagger definition "mockarty_internal_model.RabbitMQRequestContext".
type RabbitMQRequestContext struct {
	OutputProps      RabbitMQOutputProps `json:"outputProps,omitempty"`
	Exchange         string              `json:"exchange,omitempty"`
	OutputExchange   string              `json:"outputExchange,omitempty"`
	OutputQueue      string              `json:"outputQueue,omitempty"`
	OutputRoutingKey string              `json:"outputRoutingKey,omitempty"`
	OutputURL        string              `json:"outputURL,omitempty"`
	Queue            string              `json:"queue,omitempty"`
	RoutingKey       string              `json:"routingKey,omitempty"`
	ServerName       string              `json:"serverName,omitempty"`
	Conditions       []Condition         `json:"conditions,omitempty"`
	Headers          []Condition         `json:"headers,omitempty"`
	SortArray        bool                `json:"sortArray,omitempty"`
}
