// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// RabbitMQOutputProps mirrors swagger definition "mockarty_internal_model.RabbitMQOutputProps".
type RabbitMQOutputProps struct {
	AppID         string `json:"appId,omitempty"`
	ContentType   string `json:"contentType,omitempty"`
	CorrelationID string `json:"correlationId,omitempty"`
	MessageID     string `json:"messageId,omitempty"`
	ReplyTo       string `json:"replyTo,omitempty"`
	Type          string `json:"type,omitempty"`
	DeliveryMode  int64  `json:"deliveryMode,omitempty"`
	Priority      int64  `json:"priority,omitempty"`
}
