// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SafetyConfig mirrors swagger definition "internal_chaos.SafetyConfig".
type SafetyConfig struct {
	// Only allow these namespaces (if set, deny is ignored)
	AllowNamespaces []string `json:"allowNamespaces,omitempty"`
	// Namespaces that must never be targeted
	DenyNamespaces []string `json:"denyNamespaces,omitempty"`
	// Max % of pods that can be affected (0 = no limit)
	BlastRadiusPercent int64 `json:"blastRadiusPercent,omitempty"`
	// Max concurrent experiments
	MaxConcurrent int64 `json:"maxConcurrent,omitempty"`
	// Max pods that can be killed/affected at once
	MaxPodsAffected int64 `json:"maxPodsAffected,omitempty"`
	// Minimum replicas that must remain alive
	MinReplicasAlive int64 `json:"minReplicasAlive,omitempty"`
	// Automatically rollback on steady-state violation
	AutoRollback bool `json:"autoRollback,omitempty"`
	// Halt experiment if steady-state check fails
	HaltOnSteadyFail bool `json:"haltOnSteadyFail,omitempty"`
	// Require manual approval before execution
	RequireApproval bool `json:"requireApproval,omitempty"`
}
