// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// ScheduleConfig mirrors swagger definition "internal_chaos.ScheduleConfig".
type ScheduleConfig struct {
	// Cron expression for recurring experiments
	CronExpr string `json:"cronExpr,omitempty"`
	// Random jitter in seconds added to start time
	Jitter int64 `json:"jitter,omitempty"`
	// Number of repetitions (0 = infinite if cron)
	RepeatCount int64 `json:"repeatCount,omitempty"`
}
