// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SetPasswordRequest mirrors swagger definition "internal_auth.SetPasswordRequest".
type SetPasswordRequest struct {
	NewPassword string `json:"new_password"`
}
