// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SmtpRequestContext mirrors swagger definition "mockarty_internal_model.SmtpRequestContext".
type SmtpRequestContext struct {
	ServerName          string      `json:"serverName,omitempty"`
	BodyConditions      []Condition `json:"bodyConditions,omitempty"`
	HeaderConditions    []Condition `json:"headerConditions,omitempty"`
	RecipientConditions []Condition `json:"recipientConditions,omitempty"`
	SenderConditions    []Condition `json:"senderConditions,omitempty"`
	SubjectConditions   []Condition `json:"subjectConditions,omitempty"`
	SortArray           bool        `json:"sortArray,omitempty"`
}
