// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SoapRequestContext mirrors swagger definition "mockarty_internal_model.SoapRequestContext".
type SoapRequestContext struct {
	Action     string      `json:"action,omitempty"`
	Method     string      `json:"method,omitempty"`
	Path       string      `json:"path,omitempty"`
	Service    string      `json:"service,omitempty"`
	Conditions []Condition `json:"conditions,omitempty"`
	Header     []Condition `json:"header,omitempty"`
	SortArray  bool        `json:"sortArray,omitempty"`
}
