// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SOAPFault mirrors swagger definition "mockarty_internal_model.SOAPFault".
type SOAPFault struct {
	// raw XML fragment for <detail>
	Detail string `json:"detail,omitempty"`
	// optional URI
	FaultActor string `json:"faultActor,omitempty"`
	// "soap:Client" or "soap:Server"
	FaultCode string `json:"faultCode,omitempty"`
	// human-readable
	FaultString string `json:"faultString,omitempty"`
	// 400 or 500, default 500
	HTTPStatus int64 `json:"httpStatus,omitempty"`
}
