// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SocketRequestContext mirrors swagger definition "mockarty_internal_model.SocketRequestContext".
type SocketRequestContext struct {
	Event      string      `json:"event,omitempty"`
	Namespace  string      `json:"namespace,omitempty"`
	ServerName string      `json:"serverName,omitempty"`
	Conditions []Condition `json:"conditions,omitempty"`
	SortArray  bool        `json:"sortArray,omitempty"`
}
