// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SSERequestContext mirrors swagger definition "mockarty_internal_model.SSERequestContext".
type SSERequestContext struct {
	Description      string      `json:"description,omitempty"`
	EventName        string      `json:"eventName,omitempty"`
	EventPath        string      `json:"eventPath,omitempty"`
	Conditions       []Condition `json:"conditions,omitempty"`
	HeaderConditions []Condition `json:"headerConditions,omitempty"`
	SortArray        bool        `json:"sortArray,omitempty"`
}
