// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SSEEvent mirrors swagger definition "mockarty_internal_model.SSEEvent".
type SSEEvent struct {
	Data         any    `json:"data,omitempty"`
	EventName    string `json:"eventName,omitempty"`
	ID           string `json:"id,omitempty"`
	TemplatePath string `json:"templatePath,omitempty"`
	Delay        int64  `json:"delay,omitempty"`
	Retry        int64  `json:"retry,omitempty"`
}
