// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SSEEventChain mirrors swagger definition "mockarty_internal_model.SSEEventChain".
type SSEEventChain struct {
	// Цепочка событий
	Events []SSEEvent `json:"events,omitempty"`
	// Интервал heartbeat (мс, 0 = отключен)
	Heartbeat int64 `json:"heartbeat,omitempty"`
	// Размер батча для логирования (по умолчанию 10)
	LogBatch int64 `json:"logBatch,omitempty"`
	// Задержка перед повторением (мс, минимум 100мс)
	LoopDelay int64 `json:"loopDelay,omitempty"`
	// Максимальное количество циклов (0 = без ограничений, по умолчанию 100)
	MaxLoops int64 `json:"maxLoops,omitempty"`
	// Максимальное время жизни соединения в секундах (0 = по умолчанию, 1200 сек = 20 мин)
	MaxTime int64 `json:"maxTime,omitempty"`
	// Зацикливать цепочку
	Loop bool `json:"loop,omitempty"`
}
