// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SteadyStateCheck mirrors swagger definition "internal_chaos.SteadyStateCheck".
type SteadyStateCheck struct {
	Headers     map[string]string `json:"headers,omitempty"`
	Endpoint    string            `json:"endpoint,omitempty"`
	Expected    any               `json:"expected,omitempty"`
	Method      string            `json:"method,omitempty"`
	Name        string            `json:"name,omitempty"`
	Query       string            `json:"query,omitempty"`
	Type        string            `json:"type,omitempty"`
	IntervalSec int64             `json:"intervalSec,omitempty"`
	TimeoutSec  int64             `json:"timeoutSec,omitempty"`
	Tolerance   float64           `json:"tolerance,omitempty"`
}
