// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// SteadyState mirrors swagger definition "internal_chaos.SteadyState".
type SteadyState struct {
	Checks []SteadyStateCheck `json:"checks,omitempty"`
}
