// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// TargetConfig mirrors swagger definition "internal_chaos.TargetConfig".
type TargetConfig struct {
	Mode       TargetMode        `json:"mode,omitempty"`
	Selector   map[string]string `json:"selector,omitempty"`
	Deployment string            `json:"deployment,omitempty"`
	Namespace  string            `json:"namespace,omitempty"`
	NodeName   string            `json:"nodeName,omitempty"`
	PodNames   []string          `json:"podNames,omitempty"`
	Percentage int64             `json:"percentage,omitempty"`
}
