// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// TargetMode mirrors swagger definition "internal_chaos.TargetMode".
type TargetMode string

// Enumerated values for TargetMode.
const (
	TargetModeOne          TargetMode = "one"
	TargetModeRandomOne    TargetMode = "random_one"
	TargetModeAll          TargetMode = "all"
	TargetModeFixedPercent TargetMode = "fixed_percent"
)
