// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// TestRun mirrors swagger definition "internal_webui.TestRun".
type TestRun struct {
	Report                 CollectionTestReport `json:"report,omitempty"`
	CompletedAt            string               `json:"completedAt,omitempty"`
	CurrentCollectionName  string               `json:"currentCollectionName,omitempty"`
	CurrentRequestName     string               `json:"currentRequestName,omitempty"`
	ExecutorName           string               `json:"executorName,omitempty"`
	ID                     string               `json:"id,omitempty"`
	Message                string               `json:"message,omitempty"`
	Mode                   string               `json:"mode,omitempty"`
	Name                   string               `json:"name,omitempty"`
	Namespace              string               `json:"namespace,omitempty"`
	StartedAt              string               `json:"startedAt,omitempty"`
	Status                 string               `json:"status,omitempty"`
	TaskID                 string               `json:"taskId,omitempty"`
	UserID                 string               `json:"userId,omitempty"`
	CollectionIds          []string             `json:"collectionIds,omitempty"`
	CompletedRequests      int64                `json:"completedRequests,omitempty"`
	CurrentCollectionIndex int64                `json:"currentCollectionIndex,omitempty"`
	CurrentRequestIndex    int64                `json:"currentRequestIndex,omitempty"`
	Progress               int64                `json:"progress,omitempty"`
	TotalCollections       int64                `json:"totalCollections,omitempty"`
	TotalRequests          int64                `json:"totalRequests,omitempty"`
	IsOwn                  bool                 `json:"isOwn,omitempty"`
}
