// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// TestReport mirrors swagger definition "mockarty_internal_model.TestReport".
type TestReport struct {
	PreRequestResult ScriptExecutionResult `json:"preRequestResult,omitempty"`
	Protocol         APITesterProtocol     `json:"protocol,omitempty"`
	RequestData      map[string]any        `json:"requestData,omitempty"`
	ResponseData     map[string]any        `json:"responseData,omitempty"`
	TestResult       ScriptExecutionResult `json:"testResult,omitempty"`
	CollectionID     string                `json:"collectionId,omitempty"`
	CollectionName   string                `json:"collectionName,omitempty"`
	ExecutedAt       string                `json:"executedAt,omitempty"`
	ID               string                `json:"id,omitempty"`
	RequestID        string                `json:"requestId,omitempty"`
	RequestName      string                `json:"requestName,omitempty"`
	Status           string                `json:"status,omitempty"`
	Logs             []string              `json:"logs,omitempty"`
	Tests            []TestResult          `json:"tests,omitempty"`
	Duration         Duration              `json:"duration,omitempty"`
	FailedTests      int64                 `json:"failedTests,omitempty"`
	PassedTests      int64                 `json:"passedTests,omitempty"`
	TotalTests       int64                 `json:"totalTests,omitempty"`
}
