// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// TimelineEvent mirrors swagger definition "internal_chaos.TimelineEvent".
type TimelineEvent struct {
	Details any    `json:"details,omitempty"`
	Message string `json:"message,omitempty"`
	// info, warning, error
	Severity  string `json:"severity,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	// fault_injected, fault_removed, pod_killed, pod_restarted, etc.
	Type string `json:"type,omitempty"`
}
