// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// UpdateAPITokenRequest mirrors swagger definition "internal_auth.UpdateAPITokenRequest".
type UpdateAPITokenRequest struct {
	Metadata           map[string]any `json:"metadata,omitempty"`
	Description        string         `json:"description,omitempty"`
	ExpiresAt          string         `json:"expires_at,omitempty"`
	Name               string         `json:"name,omitempty"`
	Namespace          string         `json:"namespace,omitempty"`
	AllowedActions     []string       `json:"allowed_actions,omitempty"`
	RateLimitPerDay    int64          `json:"rate_limit_per_day,omitempty"`
	RateLimitPerHour   int64          `json:"rate_limit_per_hour,omitempty"`
	RateLimitPerMinute int64          `json:"rate_limit_per_minute,omitempty"`
	Enabled            bool           `json:"enabled,omitempty"`
}
