// Copyright (c) 2026 Mockarty. All rights reserved.
// Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// UserInfo mirrors swagger definition "internal_auth.UserInfo".
type UserInfo struct {
	Email           string   `json:"email,omitempty"`
	ID              string   `json:"id,omitempty"`
	Login           string   `json:"login,omitempty"`
	SystemRole      string   `json:"system_role,omitempty"`
	Namespaces      []string `json:"namespaces,omitempty"`
	Email2faEnabled bool     `json:"email_2fa_enabled,omitempty"`
	HasPassword     bool     `json:"has_password,omitempty"`
}
