// Code generated by scripts/sync-models. DO NOT EDIT.
// Source: docs/swagger/swagger.json
// Regenerate: make sync-models

package dto

// VerifyTFARequest mirrors swagger definition "internal_auth.VerifyTFARequest".
type VerifyTFARequest struct {
	Code string `json:"code,omitempty"`
	// "totp" (default) or "email"
	Method       string `json:"method,omitempty"`
	RecoveryCode string `json:"recovery_code,omitempty"`
	TFAToken     string `json:"tfa_token"`
}
